### ISSUE TITLE
Can you create a measure app of apple?

### ISSUE THREAD

**Issue by rockstardev8964** [Reality-Dev/BodyTracking#1]
I want to create an app like measure app on iPhone 12 pro.

Using RealityKit, I want to measure human body height automatically without start point.

Can we discuss about this project?

My skype : live:liming8964

Regards.

**Comment by Reality-Dev** [comment]
Hi Dev-Lee. Sorry, I am really booked up with other projects at the moment so I don't really have time to discuss further. I can offer my advice, however: I would look into [estimatedScaleFactor](https://developer.apple.com/documentation/arkit/arbodyanchor/3255162-estimatedscalefactor) which relates the body's default height [1.8 meters] with the height ARKit estimates at runtime. Alternatively you could take the measurement between joints like the foot joint and the head joint, but there is no joint for the very top of the head (the eyes are the furthest up) so you would have to add a little bit of height for that. If you were to go this route you could look into the function on the documentation [on this page](https://developer.apple.com/documentation/arkit/arbodyanchor) called `hipToFootOffset` and modify it to use head to foot or eyes to foot instead of hip to foot. Also, you could use a [Core Graphics](https://www.hackingwithswift.com/read/27/3/drawing-into-a-core-graphics-context-with-uigraphicsimagerenderer) overlay to display the UI describing the height of the person (might try using the [project](https://developer.apple.com/documentation/realitykit/arview/3243244-project) method of ARView to draw a 2D screen-space graphic corresponding to a point in 3D space), or do it any way you want. As far as the rest of the app, there are plenty of tutorials on how to do the basic parts of the measure app (Google search and Udemy go a long way), but making the experience as great as Apple's is the main challenge. Good Luck!

**Comment by rockstardev8964** [comment]
Thanks for your advice.

But I think you can create a demo in a short time based on your skills.
This is really urgent project.

So Can we discuss in private message?
Of course I will pay what you want.

Looking forward to your favorable reply.
Regards.

**Comment by Reality-Dev** [comment]
Sure we can talk about it. I will send an email to liming8964@hotmail.com if that works.

**Comment by rockstardev8964** [comment]
Thanks, I will wait your email.

**Comment by Reality-Dev** [comment]
Got it sent.
